version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: blackjack_db
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  blackjack-api:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - mongo
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/blackjack_db

volumes:
  mysql-data:
  mongo-data: