spring:
  application:
    name: blackjack

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG